spring.application.name=AegisPrev

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/AegisPrev}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:U3dsRG5yelRWSTRyUjByOEpUUlE2YkRxT0t2ekZqMkI5SkRtRlljVmh0Tg==}
jwt.expiration=${JWT_EXPIRATION:86400000}

cors.allowed-origin=${CORS_ORIGIN:http://localhost:5173}

server.port=${PORT:8080}
server.error.include-message=always
server.error.include-binding-errors=always