spring.application.name=AegisPrev

spring.datasource.url=jdbc:postgresql://localhost:5432/AegisPrev
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=U3dsRG5yelRWSTRyUjByOEpUUlE2YkRxT0t2ekZqMkI5SkRtRlljVmh0Tg==
jwt.expiration=86400000